#
# [ Database Configuration Section ]
#

spring:
  datasource:
    url: jdbc:h2:mem:APP_USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
server:
  port: 8080

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false
